config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  root "static_pages#index"
  namespace :admin do
    root "static_pages#index"
    resources :static_pages
    resources :categories
    resources :products
    resources :users, only: [:index, :show, :destroy]
  end
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index]
  resources :products, only: [:index, :show]
  resources :orders
  resources :detail_orders, only: [:create]
  mount API => '/'
end

app/models/order.rb
class Order < ActiveRecord::Base
  scope :where_status_for_admin, -> do
    where "status = ? or status = ?", statuses[:pendding], statuses[:done]
  end

  belongs_to :user
  has_many :detail_orders, dependent: :destroy

  enum status: [:created, :pendding, :done, :cancel]

  before_create :create_order
  before_save :update_total_money

  def total_money
    self.detail_orders.collect do |item|
      item.valid? ? (item.quantity * item.price) : 0
    end.sum
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |order|
        csv << order.attributes.values_at(*column_names)
      end
    end
  end

  def download_keys keys
    CSV.generate do |csv|
      csv << column_names
      keys.each do |key|
        csv << key.attributes.values_at(*column_names)
      end
    end
  end

  private
  def create_order
    self.status = :created
    self.date_update = Time.now
  end

  def update_total_money
    self.total_money = total_money
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  layout false, only: [:show]

  before_action :load_order, only: [:update]

  def index
    @q = Order.ransack params[:q]
    @orders = @q.result.where_status_for_admin
      .includes(:user).order(date_update: :desc)
      .page(params[:page]).per Settings.per_page
    @ord = get_index params[:page], Settings.per_page
    download_file params[:download] if params[:download]
    respond_to do |format|
      format.html
      format.csv {send_data @orders.to_csv}
      format.xlsx {render xlsx: 'index',filename: "orders.xlsx"}
    end
  end

  def show
    @order = Order.find_by id: params[:id]
    if @order.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def update
    if params[:order][:status].present?
      case params[:order][:status]
      when "done"
        @order.update_attributes status: :done
        flash[:success] = t "order.done"
      when "cancel"
        @order.update_attributes status: :cancel
        flash[:danger] = t "order.pay_cancel"
      else
        flash[:danger] = t "order.pay_fail"
      end
    else
      flash[:danger] = t "order.pay_fail"
    end
    redirect_to admin_orders_path
  end

  private

  def load_order
    @order = Order.find_by id: params[:id]
    if @order.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def download_file download_option
    filename = "product"
    send_data Order.all.download_keys(keys),
      type: "text/csv; charset=UTF-8; header=present",
      disposition: "attachment; filename=#{filename}"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ClientController
  before_action :authenticate_login!
  before_action :load_order, except: [:index, :create]

  def index
    @orders = Order.where(user_id: current_user.id).order(date_update: :desc)
      .page(params[:page]).per Settings.per_page
    @ord = get_index params[:page], Settings.per_page
    @order = Order.new
  end

  def show
  end

  def create
    @order = Order.new
    @order.user_id = current_user.id
    if @order.save
      session[:order_id] = @order.id
      flash[:success] = t "add_success"
      redirect_to orders_path
    else
      flash[:success] = t "add_fail"
      redirect_to orders_path
    end
  end

  def edit
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def update
    if params[:order][:status].present?
      case params[:order][:status]
      when "pendding"
        @order.update_attributes status: :pendding
        send_message @order
        CartMailer.new_cart(@order).deliver_now
        session[:order_id] = nil
        flash[:success] = t "order.pay_success"
      when "cancel"
        @order.update_attributes status: :cancel
        flash[:danger] = t "order.pay_cancel"
      else
        flash[:danger] = t "order.pay_fail"
      end
    else
      flash[:danger] = t "order.pay_fail"
    end
    redirect_to order_path @order.id
  end

  def destroy
    if @order.status == Order.statuses[:created] || Order.statuses[:cancel]
      @order.destroy
      session[:order_id] = nil
      flash[:success] = t "delete_success"
    else
      flash[:danger] = t "order.can_not_delete"
    end
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit user: current_user
  end

  def load_order
    @order = Order.find_by id: params[:id]
    if @order.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def current_order
    session[:order_id].present? ? Order.find(session[:order_id]) : Order.new
  end

  def send_message orders
    ChatWork.api_key = "b9c2ebdfd7d124e28235dca47d78649f"
    name = ChatWork::Me.get["name"]
    account_id = ChatWork::Me.get["account_id"]
    room_id = ChatWork::Me.get["room_id"]
    message_body = "[To:#{account_id}] #{name}\nWe have new order!\n"
    orders.detail_orders.select_product.each do |item|
      message_body += "Product:  #{item.name} "
      message_body += "Quantity: #{item.quantity} "
      message_body += "Price: #{item.price} \n"
      message_body += "Total money: #{item.total_money} \n"
    end
    ChatWork::Message.create room_id: room_id, body: message_body
  end
end

app/views/admin/orders/index.html.erb
<div class="portlet box manager">
  <div class="portlet-title">
    <div class="caption">
      <span class="caption-title">
        <i class="fa fa-reorder"></i><%= t "manager" %>
      </span>
      <div class="action-container top pull-right">
        <%= link_to admin_orders_path(format: :csv) do %>
          <span class="btn btn-success">Export csv</span>
        <% end %>
        <%= link_to admin_orders_path(format: :xlsx) do %>
          <span class="btn btn-success">Export excel</span>
        <% end %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="search-container">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="col-md-3">
          <%= f.search_field :name_cont_any, class: "form-control",
            placeholder: t("keyword") %>
        </div>
        <%= f.submit class: "btn btn-default btn-search-top clear" %>
      <% end %>
      <div class="clearfix"></div>
    </div>
    <div class="data-container">
      <div class="grid-data" data-size="FULL" data-size-reset="FULL"
        data-title="<%= t "update" %>">
        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th><%= t "ord" %></th>
              <th><%= t "title" %></th>
              <th><%= t "created" %></th>
              <th><%= t "status" %></th>
              <th><%= t "function" %></th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each_with_index do |order, index| %>
              <tr>
                <td class="text-center"><%= @ord+index %></td>
                <td>
                  <a class="act-view" href="javascript:;"
                    data-view="<%= admin_order_path(order)%>">
                    <%= order.user.name %>
                  </a>
                </td>
                <td><%= l order.created_at, format: :long %></td>
                <th class="<%= order.status == "pendding" ?
                  "text-danger" : order.status == "cancel" ?
                  "text-info" : "text-success" %>">
                  <%= order.status %></th>
                <td class="text-center">
                  <span class="action-order">
                    <% if order.status == "pendding" %>
                      <%= simple_form_for [:admin, order] do |f| %>
                        <%= f.hidden_field :status, value: :done %>
                        <%= f.button :submit, t("order.done"),
                          data: { confirm: t("sure")},
                          class: "btn btn-primary btn-xs" %>
                      <% end %>
                    <% end %>
                  </span>
                  <span class="action-order">
                    <% if order.status == "pendding" %>
                      <%= simple_form_for [:admin, order] do |f| %>
                        <%= f.hidden_field :status, value: :cancel %>
                        <%= f.button :submit, t("order.cancel"),
                          data: { confirm: t("sure")},
                          class: "btn btn-danger btn-xs" %>
                      <% end %>
                    <% end %>
                  </span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row wrap-paging">
          <div class="col-sm-5">
          </div>
          <div class="col-sm-7 text-right">
            <%= paginate @orders, theme: "twitter-bootstrap-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="portlet order">
  <div class="portlet-title">
    <div class="caption">
      <h4>
        <span class="text-info"><%= t "customer: "%></span><%= @order.user.name %>
      </h4>
    </div>
  </div>
  <div class="portlet-body">
    <div class="grid-content">
      <p>
        <span class="text-danger"><%= t "created: "%></span>
        <%= l @order.created_at, format: :long %>
      </p>
    </div>
      <div class="col-md-4 no-padding">
        <p>
          <span class="text-danger"><%= t "created: "%></span>
          <%= l @order.created_at, format: :short %>
        </p>
      </div>
      <div class="col-md-8 no-padding-right">
        <div class="pro-title"></div>
        <div class="list-product">
          <table class="table table-bordered table-striped table-hover">
            <thead>
              <tr>
                <th class="text-center"><%= t "ord" %></th>
                <th class="text-center"><%= t "title" %></th>
                <th class="text-center"><%= t "price" %></th>
                <th class="text-center"><%= t "quantity" %></th>
                <th class="text-center"><%= t "total amount" %></th>
              </tr>
            </thead>
            <tbody>
              <% @order.detail_orders.select_product.each_with_index do |product, index| %>
                <tr class="tr-<%= product.product_id %>">
                  <td class="text-center"><%= index+1 %></td>
                  <td>
                    <a href="<%= product_path product.product_id %>">
                      <%= product.name %>
                    </a>
                  </td>
                  <td class="text-right"><%= product.price %></td>
                  <td class="text-center">
                    <% if @order.status == "created" || @order.status == "cancel" %>
                      <%= link_to "-", "javascript:;",
                        class: "btn btn-sm btn-default pull-left btn-sub-product",
                        data: {id: product.product_id, url: detail_order_path,
                        order: @order.id} %>
                    <% end %>
                    <span id="quantity-<%= product.product_id %>">
                      <%= product.quantity %>
                    </span>
                    <% if @order.status == "created" || @order.status == "cancel" %>
                      <%= link_to "+", "javascript:;",
                        class: "btn btn-sm btn-default pull-right btn-add-product",
                        data: {id: product.product_id, url: detail_order_path,
                        order: @order.id} %>
                    <% end %>
                  </td>
                  <td class="text-right total-<%= product.product_id %>">
                    <%= product.quantity * product.price %>
                  </td>
                </tr>
              <% end %>
              <% if @order.status == "pendding" || @order.status == "done" %>
                <tr>
                  <td colspan="4"><b><%= t "total" %></b></td>
                  <td class="text-right"><%= @order.total_money %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>