config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  root "static_pages#index"
  namespace :admin do
    root "static_pages#index"
    resources :static_pages
    resources :categories
    resources :products
    resources :users, only: [:index, :show, :destroy]
  end
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index]
  resources :products, only: [:index, :show]
  resources :orders
  resources :detail_orders, only: [:create]
  mount API => '/'
end

app/models/category.rb
class Category < ActiveRecord::Base
  scope :where_contains, -> keyword {where("title like ?","%#{keyword}%")}

  has_many :products

  validates :title, uniqueness: true, presence: true, length: {maximum: 100}
  validates :description, length: {maximum: 200}

  def verify_destroy_category
    if self.products.any?
      errors.add "category", I18n.t("category.can_not_delete")
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  include ApplicationHelper

  layout false, only: [:new, :edit, :show]

  before_action :load_category, except: [:index, :create, :new]

  def index
    @categories = Category.where_contains(params["keyword"]).includes(:products).
      order(created_at: :desc).page(params[:page]).per Settings.per_page
    @ord = get_index params[:page], Settings.per_page
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
      if @category.save
        flash[:success] = t "add_success"
      end
    redirect_to admin_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "update_success"
    end
      redirect_to admin_categories_path
  end

  def destroy
    if @category.verify_destroy_category
      flash[:danger] = t "category.can_not_delete"
    else
      @category.destroy
      flash[:success] = t "delete_success"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :title, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div class="field">
    <div class="form-group">
      <%= f.label :title, t("title"), class: "text-default" %>
      <%= f.label :title, t("required"), class: "text-danger" %>
      <%= f.text_field :title, placeholder: t("title"),
        required: "required", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_area :description, placeholder: t("product.description"), rows: 8,
        class: "form-control" %>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render "form" %>

app/views/admin/categories/index.html.erb
<div class="portlet box manager">
  <div class="portlet-title">
    <div class="caption">
      <span class="caption-title">
        <i class="fa fa-reorder"></i><%= t "manager" %>
      </span>
      <div class="action-container top pull-right">
        <button data-size="FULL" data-title="<%= t "add" %>"
          data-url="<%= new_admin_category_path %>" class="act-add btn btn-success">
          <%= t "add" %></button>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="search-container">
      <%= form_tag admin_categories_path, method: :get do %>
        <div class="col-md-3">
          <%= text_field_tag :keyword, params[:keyword], class: "form-control",
            placeholder: t("keyword") %>
        </div>
        <%= submit_tag t("search"),
          class: "btn btn-default btn-search-top clear" %>
        <% end %>
      <div class="clearfix"></div>
    </div>
    <div class="data-container">
      <div class="grid-data" data-size="FULL" data-size-reset="NORMAL"
        data-title="<%= t "update" %>">
        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th><%= t "ord" %></th>
              <th><%= t "title" %></th>
              <th><%= t "created" %></th>
              <th><%= t "function" %></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each_with_index do |category, index| %>
              <tr>
                <td class="text-center"><%= @ord+index %></td>
                <td>
                  <a class="act-view" href="javascript:;"
                    data-view="<%= admin_category_path(category)%>">
                    <%= category.title %>
                  </a>
                  <span class="badge"><%= category.products.size %></span>
                </td>
                <td><%= l category.created_at, format: :long %></td>
                <td class="text-center">
                  <%= link_to "#", title: t("edit"), class: "act-edit text-success",
                    data: {url: edit_admin_category_path(category)} do %>
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to [:admin, category], method: :delete, title: t("delete"),
                    class: "underline text-danger", data: {confirm: t("sure")} do %>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row wrap-paging">
          <div class="col-sm-5">
          </div>
          <div class="col-sm-7 text-right">
            <%= paginate @categories, theme: "twitter-bootstrap-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<%= render "form" %>

app/views/admin/categories/show.html.erb
<div class="portlet category">
  <div class="portlet-title">
    <div class="caption">
      <h4>
        <span class="text-danger"><%= t "title: "%></span><%= @category.title %>
      </h4>
    </div>
  </div>
  <div class="portlet-body">
    <div class="grid-content">
      <p>
        <span class="text-danger"><%= t "created: "%></span>
        <%= l @category.created_at, format: :long %>
      </p>
    </div>
  </div>
</div>