config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  root "static_pages#index"
  namespace :admin do
    root "static_pages#index"
    resources :static_pages
    resources :categories
    resources :products
    resources :users, only: [:index, :show, :destroy]
  end
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: [:show, :index]
  resources :products, only: [:index, :show]
  resources :orders
  resources :detail_orders, only: [:create]
  mount API => '/'
end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :where_contains, -> keyword {where("name like ?","%#{keyword}%")}

  mount_uploader :avatar, AvatarUploader
  belongs_to :category
  has_many :comments
  has_many :detail_orders

  validates :name, presence: true, uniqueness:true, length: {maximum: 50}
  validates :quantity, numericality: true, allow_nil: true
  validates :price, numericality: true, allow_blank: true
  validates :category_id, presence: true
  validate :image_size_validation

  ratyrate_rateable "rate"

  private
  def image_size_validation
    if avatar.size > Settings.avatar.bytes_image
      errors.add "avatar_size:", I18n.t("product.image_size_error")
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  include ApplicationHelper

  layout false, only: [:new, :edit, :show]

  before_action :load_categories, except: [:index, :destroy]
  before_action :load_product, except: [:index, :create, :new]

  def index
    @q = Product.ransack params[:q]
    @products = @q.result
      .includes(:comments).order(created_at: :desc)
      .page(params[:page]).per Settings.per_page
    @ord = get_index params[:page], Settings.per_page
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "add_success"
    else
      flash[:danger] = t "add_fail"
    end
    redirect_to admin_products_path
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "update_success"
    end
    redirect_to admin_products_path
  end

  def destroy
    if @product.destroy
      flash.now[:success] = t "delete_success"
    else
      flash.now[:danger] = t "product.can_not_delete"
    end
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product)
      .permit :name, :description, :price, :avatar, :category_id, :remove_avatar
  end

  def load_categories
    @categories = Category.all
  end

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ClientController
  def index
    if params["cate"].present? && params["cate"] != ""
      @products = Product.where(category_id: params["cate"]).
        where_contains(params["keyword"]).
        order(created_at: :desc).page(params[:page]).per Settings.per_page
    else
      @products = Product.where_contains(params["keyword"]).
      order(created_at: :desc).page(params[:page]).per Settings.per_page
    end
    @categories = Category.all
  end

  def show
    @product = Product.find_by id: params[:id]
    @comment = Comment.new product: @product
    @comments = @product.comments.order(created_at: :desc)
      .page(params[:page]).per Settings.per_page
    if @product.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :category_id, collection: @categories, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <%= f.input :price, class: "form-control" %>
  <% if f.object.avatar? %>
    <%= image_tag f.object.avatar.thumb.url %>
    <%= f.input :remove_avatar, as: :boolean,
      checked_value: true, unchecked_value: false %>
    <%= f.label :remove_avatar %>
  <% end %>
  <%= f.input :avatar, class: "form-control" %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="field">
  <%= render "form" %>
</div>

app/views/admin/products/index.html.erb
<div class="portlet box manager">
  <div class="portlet-title">
    <div class="caption">
      <span class="caption-title">
        <i class="fa fa-reorder"></i><%= t "manager" %>
      </span>
      <div class="action-container top pull-right">
        <button data-size="FULL" data-title="<%= t "add" %>"
          data-url="<%= new_admin_product_path %>" class="act-add btn btn-success">
          <%= t "add" %></button>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="search-container">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="col-md-3">
          <%= f.search_field :name_cont_any, class: "form-control",
            placeholder: t("keyword") %>
        </div>
        <%= f.submit class: "btn btn-default btn-search-top clear" %>
      <% end %>
      <div class="clearfix"></div>
    </div>
    <div class="data-container">
      <div class="grid-data" data-size="FULL" data-size-reset="NORMAL"
        data-title="<%= t "update" %>">
        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th><%= t "ord" %></th>
              <th><%= t "name" %></th>
              <th><%= t "product.price" %></th>
              <th><%= t "category.title" %></th>
              <th><%= t "created_at" %></th>
              <th><%= t "function" %></th>
            </tr>
          </thead>
          <tbody>
            <% @products.each_with_index do |product, index| %>
              <tr>
                <td class="text-center"><%= @ord+index %></td>
                <td>
                  <a class="act-view" href="javascript:;"
                    data-view="<%= admin_product_path(product)%>">
                    <%= product.name %>
                  </a>
                  <% if product.comments.length > 0 %>
                    <span class="badge">
                      <%= product.comments.length.to_s + t("comments") %>
                    </span>
                  <% end %>
                </td>
                <td class="text-center"><%= product.price %></td>
                <td class="text-center"><%= product.category.title %></td>
                <td class="text-center"><%= l product.created_at, format: :long %></td>
                <td class="text-center">
                  <%= link_to "#", title: t("edit"), class: "act-edit text-success",
                    data: {url: edit_admin_product_path(product)} do %>
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to [:admin, product], method: :delete, title: t("delete"),
                    class: "underline text-danger", data: {confirm: t("sure")} do %>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row wrap-paging">
          <div class="col-sm-5">
          </div>
          <div class="col-sm-7 text-right">
            <%= paginate @products, theme: "twitter-bootstrap-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="field">
  <%= render "form" %>
</div>

app/views/admin/products/show.html.erb
<div class="portlet view">
  <div class="portlet-title">
    <div class="caption">
      <h4>
        <span class="text-danger"><%= "#{t "title"}: " %></span><%= @product.name %>
      </h4>
    </div>
  </div>
  <div class="portlet-body">
    <div class="grid-content">
      <div>
        <div class="col-md-6 ">
          <p>
            <span class="text-danger"><%= "#{t "category.title"}:" %></span>
            <%= @product.category.title %>
          </p>
          <p>
            <span class="text-danger"><%= "#{t "product.description"}:" %></span>
            <%= @product.description %>
          </p>
          <p>
            <span class="text-danger"><%= "#{t "product.quantity"}:" %></span>
            <%= @product.quantity %>
          </p>
          <p>
            <span class="text-danger"><%= "#{t "product.rate"}:" %></span>
            <%= @product.average("rate").avg %>
          </p>
          <p>
            <span class="text-danger"><%= "#{t "product.total_rate"}:" %></span>
            <%= @product.rates("rate").count %>
          </p>
          <p>
            <span class="text-danger"><%= "#{t "created"}:" %></span>
            <%= l @product.created_at, format: :long %>
          </p>
        </div>
        <div class="col-md-5 col-md-offset-1">
          <p>
            <img src="<%= @product.avatar.thumb %>">
          </p>
        </div>
      </div>

    </div>
  </div>
  <div class="clearfix"></div>
</div>